/*
 * Copyright 2016 riddles.io (developers@riddles.io)
 *
 *     Licensed under the Apache License, Version 2.0 (the "License");
 *     you may not use this file except in compliance with the License.
 *     You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 *     Unless required by applicable law or agreed to in writing, software
 *     distributed under the License is distributed on an "AS IS" BASIS,
 *     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *     See the License for the specific language governing permissions and
 *     limitations under the License.
 *
 *     For the full copyright and license information, please view the LICENSE
 *     file that was distributed with this source code.
 */

package io.riddles.javainterface.engine;

import io.riddles.javainterface.configuration.CheckedConfiguration;
import io.riddles.javainterface.configuration.Configuration;
import io.riddles.javainterface.exception.ConfigurationException;
import io.riddles.javainterface.exception.TerminalException;

import io.riddles.javainterface.game.player.PlayerProvider;
import io.riddles.javainterface.io.BotIO;
import io.riddles.javainterface.io.BotIOHandler;
import org.json.JSONObject;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Logger;

import io.riddles.javainterface.game.player.AbstractPlayer;
import io.riddles.javainterface.game.processor.AbstractProcessor;
import io.riddles.javainterface.game.state.AbstractState;
import io.riddles.javainterface.io.IO;

/**
 * io.riddles.javainterface.engine.AbstractEngine - Created on 2-6-16
 *
 * DO NOT EDIT THIS FILE
 *
 * The engine in the main project should extend this abstract class.
 * This class handles everything the game engine needs to do to start, run and finish.
 * Quite a lot of methods have already been implemented, but some need to
 * be Overridden in the Subclass. An object of the Subclass of AbstractEngine should
 * be created in the Main method of the project and then the engine is started with
 * engine.run()
 *
 * @author Jim van Eeden - jim@riddles.io
 */
public abstract class AbstractEngine<Pr extends AbstractProcessor,
        Pl extends AbstractPlayer, S extends AbstractState> {//} implements EngineLifecycle {

    protected final static Logger LOGGER = Logger.getLogger(AbstractEngine.class.getName());

    protected IO ioHandler;
    protected PlayerProvider<Pl> playerProvider;

    protected Pr processor;

    protected GameLoop gameLoop;

    protected AbstractEngine(PlayerProvider<Pl> playerProvider, IO ioHandler ) throws TerminalException {
        this.playerProvider = playerProvider;
        this.gameLoop = createGameLoop();

        this.ioHandler = ioHandler;
    }



    /**
     * Does everything needed before the game can start, such as
     * getting the amount of players, setting the processor and sending
     * the game settings to the bots.
     */
    public S willRun() throws TerminalException {
        LOGGER.info("Setting up engine. Waiting for initialize...");

        this.ioHandler.waitForMessage("initialize");
        this.ioHandler.sendMessage("ok");

        LOGGER.info("Got initialize. Parsing settings...");
        CheckedConfiguration configuration = getConfiguration();
        parseInputUntilStart(configuration);
        if (!configuration.isComplete()) {
            throw new ConfigurationException("Configuration incomplete.");
        }

        this.processor = createProcessor();

        LOGGER.info("Got start. Sending game settings to bots...");

        sendConfigurationToPlayers(this.playerProvider.getPlayers(), configuration);
        LOGGER.info("Settings sent. Setting up engine done...");

        return getInitialState(configuration);

    }

    protected void parseInputUntilStart(Configuration configuration) throws TerminalException {
        InputParser parser = new InputParser();
        try {
            ParseResult p;
            String line = "";
            p = parser.parse(line);
            while (p.getType() != InputType.START) { // from "start", setup is done
                line = this.ioHandler.getNextMessage();
                p = parser.parse(line);
                switch (p.getType()) {
                    case BOT_IDS:
                        for(Integer bot_id : (ArrayList<Integer>)p.getValue()) {
                            Pl player = createPlayer(bot_id, new BotIOHandler(bot_id));
                            this.playerProvider.add(player);
                        }
                        break;
                    case CONFIGURATION:
                        JSONObject config = (JSONObject)p.getValue();
                        Iterator<String> keys = config.keys();
                        while (keys.hasNext()) {
                            String key = keys.next();
                            JSONObject configValue = (config.getJSONObject(key));
                            configuration.put(key, configValue);
                        }
                        break;
                }
            }
        } catch (IOException ex) {
            throw new TerminalException(ex.getMessage());
        }
    }

    /**
     * Send the settings to the player (bot) that are specific to this game
     *
     * @param player Player to send the configuration to
     * @param configuration Configuration to send

     */
    protected abstract void sendConfigurationToPlayer(Pl player, Configuration configuration);
    /**
     * Send the settings to the player (bot) that are specific to this game
     *
     * @param List<Pl> players to send the settings to
     * @param configuration Configuration to send
     */

    protected void sendConfigurationToPlayers(List<Pl> players, Configuration configuration) {
        players.forEach(p -> this.sendConfigurationToPlayer(p, configuration));
    }

    /**
     * This method starts the engine.
     */
    public S run(S initialState) throws TerminalException, InterruptedException {
        LOGGER.info("Running Engine...");

        if (this.processor == null) {
            throw new TerminalException("Processor has not been set");
        }

        LOGGER.info("Starting game loop...");

        this.gameLoop.run(initialState, this.processor);
        return initialState;
    }

    public void didRun(S finalState) {

        // let the wrapper know the game has ended
        this.ioHandler.sendMessage("end");

        // send game details
        this.ioHandler.waitForMessage("details");

        Integer winner = this.processor.getWinnerId(finalState);
        String winnerId = "null";

        if (winner != null) {
            winnerId = String.valueOf(winner);
        }

        JSONObject details = new JSONObject();
        details.put("winner", winnerId);
        details.put("score", this.processor.getScore(finalState));

        this.ioHandler.sendMessage(details.toString());

        // send the game file
        this.ioHandler.waitForMessage("game");

        String playedGame = getPlayedGame(finalState);
        this.ioHandler.sendMessage(playedGame);
    }

    /**
     * Implement this to create a CheckedConfiguration for the app.
     *
     * @return The CheckedConfiguration of the game
     */
    protected abstract CheckedConfiguration getConfiguration();

    /**
     * Implement this to return the initial (mostly empty) game state.
     * @param Configuration configuration
     * @return The initial state of the game, should be Subclass of AbstractState
     */
    protected abstract S getInitialState(Configuration configuration);

    /**
     * Implement this to return a player in the game.
     *
     * @param id Id of the player
     * @param BotIO ioHandler that handles IO.
     * @return Object that is Subclass of AbstractPlayer
     */
    protected abstract Pl createPlayer(int id, BotIO ioHandler);

    /**
     * Implement this to return the processor for the game.
     *
     * @return Object that is Subclass of AbstractProcessor
     */
    protected abstract Pr createProcessor();

    /**
     * Implement this to return the GameLoop for the game.
     *
     * @return Object that is Subclass of GameLoop
     */
    protected abstract GameLoop createGameLoop();

    /**
     * Return the string representation of the entire game to use in
     * the visualizer
     *
     * @param initialState The initial state of the game (can be used
     *                     to go the next game states).
     * @return String representation of the entire game
     */
    protected abstract String getPlayedGame(S initialState);

    /**
     * @return The players for the game
     */
    public PlayerProvider getPlayerProvider() {
        return this.playerProvider;
    }

    /**
     * @return The processor for the game
     */
    public Pr getProcessor() {
        return this.processor;
    }
}


